### ISSUE TITLE
can this be implemented without using BA to manage your content

### ISSUE THREAD

**Issue by kmjgallo** [brightsign/video-mode-plugin#4]
hi not an issue but a question, I understand this is to be used with BA connected but I use SignageLive as the CMS not BA, can the file be manually loaded to the SD card on the player to customize the output resolution?  Will be connecting a series 5 player to a Nanolumens wall at 4480 x 990 which Brightsign has confirmed will work with the player.

**Comment by bhastings1019** [comment]
Hi @kmjgallo - Thank you for your patience. For additional inquiries, emailing support@brightsign.biz is also a helpful resource when working with BrightSign's products or any of our CMS Partners. 

The resolution of the player could be set via a script or a function as part of the application running. Signagelive may have their recommended approach for how their application and authoring tool handles setting custom resolutions. 

It looks like this question may have been answered by our team - if this is incorrect, just let me know and we can reopen this Github Issue or discuss further in Zendesk. 

Thank you!
