### ISSUE TITLE
rgb black levels

### ISSUE THREAD

**Issue by cybermatrix84** [brightsign/video-mode-plugin#5]
Im trying to change levels to rgb full range by edit setsinglescreenvideomode.brs but brightsign tell syntax error via log. please help me on video mode

this is the script that i change
#############################################################################################
' Single Screen VideoMode Plugin
' Plugin function name - SetVideoMode
' Plugin return type - As String
' Implementation Description - This function is intended to be used by BrightAuthor:connected or BrightAuthor, to 
' expose further video settings beyond the authoring applications. 
' The return string of this function will be directly passed to `SetVideoMode()` as the parameter in the presentation autorun.

' See BrightSign docs for a list of supported video modes - https://brightsign.atlassian.net/wiki/spaces/DOC/pages/370676833/Supported+Video+Modes

' Note: This plugin assumes it is executed on BrightSign Model with a single HDMI output.
' This will NOT work on a BrightSign Model with multiple HDMI outputs.

Function SetVideoMode(videoModeInputs, bsp) As String

  print "video mode plugin, Series 4 or earlier: SetVideoMode()"
  ' Example: manage the options of a supported video mode
  ' See options you can set - https://brightsign.atlassian.net/wiki/spaces/DOC/pages/370672969/roVideoMode#roVideoMode-SetMode(modeAsString)AsBooleansetmode
  ' return "1920x1080x60p:rgb:fullrange"

  ' Example: set the video mode to be a custom mode.
  ' Custom Modelines allow the player to play back video modes that are not natively supported in BrightAuthor:connected or BrightAuthor's Video Resolution
  ' down and not listed under https://brightsign.atlassian.net/wiki/spaces/DOC/pages/370676833/Supported+Video+Modes.
  ' These are considered, "custom".
  ' The following code block is a example of and how to generate or grab the modeline - https://brightsign.atlassian.net/wiki/spaces/DOC/pages/420217686/Applying+a+Custom+Resolution
  'vm = CreateObject("roVideoMode")
  'vm.SetCustomModeline("Modeline 1440x1920x50p 151.83 1440 1490 1510 1554  1920 1935 1939 1954  -hsync -vsync")
  return "3840x2160x60p:rgb:fullrange"

End Function

**Comment by bhastings1019** [comment]
@cybermatrix84 Could you provide the error from the log? 

To confirm, the `setsinglescreenvideomode.brs` was [added to a BrightAuthor:connected or BrightAuthor presentation](https://github.com/brightsign/video-mode-plugin/tree/master#video-mode-plugin-usage)? 

Here is additional information when adding a [video mode plugin to BrightAuthor:connected](https://brightsign.atlassian.net/wiki/spaces/DOC/pages/404623943/Presentation+Settings#Video-Mode-Plugin).

**Comment by cybermatrix84** [comment]
@bhastings1019 
Sorry for late reply, im using brightAuthor presentation.  i already set function name SetVideoMode, also i noticed that function As String is for series 4 and As Object for series 5. i had XD235 so after tried As String i also tried As Object but the result is same. can you check if my script syntax looks okay.

i forgot to capture the log. after several tries i got no error but my interactive playlist didnt work also brightsign is always restarting. 

i will capture log again as soon as i try it again. thankyou so much before

**Comment by bhastings1019** [comment]
@cybermatrix84 Would you be able to [_Contact Support_](https://www.brightsign.biz/resources/request-support/) or email _support@brightsign.biz_ to include BrightSign Support? Reference this Github Issue number to provide context. 

They will ask for your updated plugins for both the Series 4 and Series 5 players, and the .bpfx or .bpf file associated with the presentation? Is this a BrightAuthor or a BrightAuthor:connected presentation? 

Thank you!

**Comment by cybermatrix84** [comment]
@bhastings1019 thankyou so much

**Comment by bhastings1019** [comment]
Closing this issue for now. If there are continued issues, please re-open this or create a new issue. The most rapid responses at the time of writing this, would be to email support@brightsign.biz. Thank you!
